import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import styled from "styled-components"
import ChatScreen from "../components/ChatScreen"


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </Container>
  )
}

const Container = styled.div``

